[LightDM]
start-default-seat=true
logind-check-graphical=false
minimum-vt=7

[Seat:*]
autologin-user=user
autologin-user-timeout=0
autologin-session=xfce
user-session=xfce
greeter-session=lightdm-gtk-greeter
xserver-command=X -nolisten tcp
