Section "Device"
    Identifier "CheerpX KMS"
    Driver "modesetting"
    Option "AccelMethod" "none"
    Option "ShadowFB" "true"
    Option "DRI" "0"
EndSection

Section "Extensions"
    Option "Composite" "Disable"
EndSection
